### ISSUE TITLE
RE: Akalath Quarantine (3023.js) in/out mech doesn't appear to work

### ISSUE THREAD

**Issue by Shiriko-star** [Multarix/tera-guide-revised#3] opened 2020-10-14 12:41 UTC
Still getting the same issue with fresh install of your guide. I've confirmed that the latest commits were applied correctly but same problem. It doesn't always occur for every in/out (i.e. sometimes it works properly, or at least "OUT" does) but I've not had 1 Akalath Travan run where every in/out was signaled correctly.

**Comment by Multarix** [comment] 2020-10-14 20:40
This is strange, the issue last time was due to the abnormal function. If you die it won't say anything..
Okay, question, does this happen with HSDN's guide too? If so I think I know the issue.

**Comment by Lachelith** [comment] 2020-10-14 20:51
Yeah I think it does. Or at least the very first IN/OUT doesn't function correctly on HSDN's sometimes.

**Comment by Multarix** [comment] 2020-10-14 21:11
this may or may not have been caused by me not passing mod through every sendMessage function... It seems fixed? Let me know, I can't get an IM party to test right now lol

**Comment by Lachelith** [comment] 2020-10-14 21:12
I will test now.

**Comment by Lachelith** [comment] 2020-10-14 21:36
Okay tested. This time the messages functioned correctly thanks!, but there was a back-to-back change (IN) then, another IN/OUT boss mech and it said 'OUT, blue IN', I went out and died... Maybe the abnormality needs clearing or something. Testing in a 2nd AQ it worked fine though (but there wasn't a back-to-back IN/OUT)

**Comment by Multarix** [comment] 2020-10-14 21:40
haha, I think you got caught with what it actually said.
I changed the messages slightly to tell you what color was inside, if you feel that might be a bit to confusing I can change it back to the color that you're supposed to be standing on.
![image](https://user-images.githubusercontent.com/29752805/96048222-a7176900-0eb9-11eb-86b5-2f8ced934594.png)

**Comment by Lachelith** [comment] 2020-10-14 21:50
No no, I might not be the most reliable source, but the IN/OUT occured twice (it can definitely happen due to whatever dictates the boss mechs server-side). I went IN as the module said, and didn't die. Then came the infrequent occurence, an additional IN/OUT, where it said "OUT" and I died..
Though on a side note I would prefer IN or OUT, I'll keep my eyes to see if the issue reoccurs or if I'm going mad.

**Comment by Multarix** [comment] 2020-10-14 21:54
Okay sure thing, I'll change it back then. I'll close this for now, be sure to reopen it if the issue happens again. As far as I can tell there shouldn't be any more issues relating to it. We will see though!
Also I hate to say it, but it's possible you had some lag spike. If that was the case, there is nothing I can do.

**Closed as completed by Multarix** 2020-10-14 21:54 UTC

**Comment by justkeepquiet** [comment] 2020-10-15 16:15
This problem is caused by the fact that your script does not have a hook to handle the event entry `"ns-3023-1000"`, due to which the function `firstboss_start_event()` is not executed. 
You need to add a hook `S_SPAWN_NPC` or go back to the old entry, like `"h-3023-1000-99"`.

Also look at the entry `"ae-0-0-99020020"`, it needs proper handling of abnormals in this part of the code:
https://github.com/Multarix/tera-guide-revised/blob/67fe66c493428b9ff40843fd52375c9fdb43c60a/modules/abnormals.js#L21

**Comment by Multarix** [comment] 2020-10-15 21:03
Somewhat incorrect. debuff was already set to 0, so running the firstboss event was not an issue unless the party wiped, I just added the hp event back in the event your party for some reason wipes in AQ. On top of that, the abnormal key for the removal of the debuff is w/e. I added a death and ressurection event which works better imo.

**Comment by justkeepquiet** [comment] 2020-10-16 17:51
A entries like `"ae-0-0-99020020"` is the old Michengs code (he didn't know about tera-game-state?).
We also planned to get away from this by integrating events from the game-state. It's already done.
